version: "3.8"
services:
  book-rent-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
